name: SAST

on:
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    name: Semgrep scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config auto --error --severity ERROR .